// let a = first.getAttribute("class")
// console.log(a)
// console.log(first.hasAttribute("class"))
// console.log(first.hasAttribute("name"))
// // first.setAttribute("hidden","true")
// // first.setAttribute("class"," right wrong")
// // first.setAttribute("class"," right")
// // first.setAttribute("id","new")
// // first.removeAttribute("class")
// console.log(first.attributes)